spring:
  application:
    name: REST_proj

  datasource:
    url: <your db URL>
    driver-class-name: org.postgresql.Driver
    username: <your db username>
    password: <your db password>

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true